# Generated by Django 3.1.4 on 2021-01-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_model',
            fields=[
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'company_db',
            },
        ),
        migrations.CreateModel(
            name='jobs_model',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_tittle', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('Experience', models.IntegerField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='application.company_model')),
            ],
            options={
                'db_table': 'jobs_db',
            },
        ),
    ]
