# Generated by Django 3.1.4 on 2021-01-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210101_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_model',
            name='company_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company_model',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
