# Generated by Django 3.1.4 on 2021-01-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20210101_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs_model',
            old_name='company_name',
            new_name='company_id',
        ),
    ]
